# Generated by Django 3.0.7 on 2020-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.CharField(max_length=20)),
                ('Stud_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('stud_class', models.CharField(max_length=10)),
            ],
        ),
    ]
